#@data/values

---
service: authorization-service
container: us-docker.pkg.dev/joshlong/mogul-artifact-registry/authorization-service:latest
url: auth.media-mogul.io
port: 8080
probes:
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness

