apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mogul-service
  name: mogul-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mogul-service
  template:
    metadata:
      labels:
        app: mogul-service
    spec:
      containers:
        - image: us-docker.pkg.dev/joshlong/mogul-artifact-registry/mogul-service:latest
          imagePullPolicy: Always
          name: mogul-service

          startupProbe:
            failureThreshold: 100
            periodSeconds: 10
            httpGet:
              port: 8080
              path: /actuator/health/readiness

          readinessProbe:
            failureThreshold: 100
            periodSeconds: 10
            httpGet:
              port: 8080
              path: /actuator/health/readiness

          livenessProbe:
            failureThreshold: 100
            periodSeconds: 10
            httpGet:
              port: 8080
              path: /actuator/health/liveness

          #          envFrom:
          #            - secretRef:
          #                name: joshlong-authorization-api-secrets

          env:

            - name: SERVER_PORT
              value: "8080"
            - name: LANG
              value: "en_US.UTF-8"

          ports:
            - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: mogul-service
  name: mogul-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: mogul-service
  type: LoadBalancer