apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization-service
  template:

    metadata:
      labels:
        app: authorization-service
    spec:
      containers:
        - name: authorization-service-container
          image: us-docker.pkg.dev/joshlong/mogul-artifact-registry/authorization-service:latest
          envFrom:
            - secretRef:
                name: mogul-secrets
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: LANG
              value: "en_US.UTF-8"

---
apiVersion: v1
kind: Service
metadata:
  name: authorization-service-service
spec:
  type: NodePort
  selector:
    app: authorization-service
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authorization-service-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "mogul-authorization-service-ip"
    networking.gke.io/managed-certificates: "false"
spec:
  rules:
    - http:
        paths:
          - pathType: ImplementationSpecific
            path: "/*"
            backend:
              service:
                name: authorization-service-service
                port:
                  number: 8080
