#@data/values

---
service: authorization-service
container: us-docker.pkg.dev/joshlong/mogul-artifact-registry/authorization-service:latest
url: auth.media-mogul.io
port: 8080
probes:
  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 60
    httpGet:
      port: 8080
      path: /actuator/health/readiness
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 60
    httpGet:
      port: 8080
      path: /actuator/health/liveness
