#@data/values

---
service: api
container: us-docker.pkg.dev/joshlong/mogul-artifact-registry/api:latest
url: api.mogul.tools
port: 8080
replicas: 1
resources:
  limits:
    cpu: "1000m"
    memory: "3Gi"
  requests:
    cpu: "1000m"
    ephemeral-storage: "10Gi"
    memory: "3Gi"
