#@data/values

---
service: mogul-podcast-audio-processor
url: podcast-audio-processor.media-mogul.io
container: us-docker.pkg.dev/joshlong/mogul-artifact-registry/mogul-podcast-audio-processor:latest
port: 7070
resources:
  limits:
    cpu: "1000m"
    memory: "10Gi"
  requests:
    cpu: "1000m"
    ephemeral-storage: "5Gi"
    memory: "10Gi"
probes:
  readinessProbe:
    httpGet:
      port: 7070
      path: /
  livenessProbe:
    httpGet:
      port: 7070
      path: /
