#@data/values-schema
#@ load("@ytt:data", "data")
---
service: ""
container: ""
url: ""
port: 8080
probes:
  readinessProbe:
    initialDelaySeconds: 120
    periodSeconds: 120
    httpGet:
      port: 8080
      path: /actuator/health/readiness
  livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 120
    httpGet:
      port: 8080
      path: /actuator/health/liveness

