name: Deploy

env:

  GCLOUD_SA_KEY:  ${{ secrets.GCLOUD_SA_KEY }}
  GCLOUD_PROJECT: joshlong
  GH_PAT: ${{ secrets.MOGUL_GITHUB_PERSONAL_ACCESS_TOKEN }}

on:
  repository_dispatch:
    types: update-event
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build-and-deploy:
    name: Build Container
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_SA_KEY }}'

      - run: |
          gcloud config set project $GCLOUD_PROJECT 
          gcloud --quiet auth configure-docker us-docker.pkg.dev


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Google Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ env.GCLOUD_SA_KEY }}

      - name: Publish Container
        run: echo "running the pipeline"
