name: Deploy

env:

  GCLOUD_SA_KEY:  ${{ secrets.GCLOUD_SA_KEY }}
  GH_PAT: ${{ secrets.MOGUL_GITHUB_PERSONAL_ACCESS_TOKEN }}
  GCLOUD_PROJECT: joshlong
  GKE_NAME: joshlong

on:
  repository_dispatch:
    types: update-event
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build-and-deploy:
    name: Build Container
    runs-on: ubuntu-latest
    steps:


      - uses: actions/checkout@v3

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_SA_KEY }}'

      - run: |
          gcloud config set project $GCLOUD_PROJECT 
          gcloud --quiet auth configure-docker us-docker.pkg.dev

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 21

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'
          project_id: ${{ env.GCLOUD_PROJECT  }}
          service_account_key: ${{ env.GCLOUD_SA_KEY }}
          export_default_credentials: true

      - name: 'Use gcloud CLI'
        run:  gcloud info

      - name: Configure kubectl
        run: gcloud container clusters get-credentials $GKE_NAME --zone us-east4 --project $GCLOUD_PROJECT

      - name: Deploy
        run: $GITHUB_WORKSPACE/bin/deploy.sh
